2024-02-06 08:59:17,738 [1;36mINFO[1;0m MainThread:180571 [wandb_setup.py:_flush():76] Current SDK version is 0.16.2
2024-02-06 08:59:17,738 [1;36mINFO[1;0m MainThread:180571 [wandb_setup.py:_flush():76] Configure stats pid to 180571
2024-02-06 08:59:17,738 [1;36mINFO[1;0m MainThread:180571 [wandb_setup.py:_flush():76] Loading settings from /home/gert/.config/wandb/settings
2024-02-06 08:59:17,738 [1;36mINFO[1;0m MainThread:180571 [wandb_setup.py:_flush():76] Loading settings from /home/gert/ALPs_with_SWYFT/notebooks/stability_checks/all/wandb/settings
2024-02-06 08:59:17,738 [1;36mINFO[1;0m MainThread:180571 [wandb_setup.py:_flush():76] Loading settings from environment variables: {}
2024-02-06 08:59:17,738 [1;36mINFO[1;0m MainThread:180571 [wandb_setup.py:_flush():76] Applying setup settings: {'_disable_service': False}
2024-02-06 08:59:17,738 [1;36mINFO[1;0m MainThread:180571 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program': '<python with no main file>'}
2024-02-06 08:59:17,738 [1;36mINFO[1;0m MainThread:180571 [wandb_init.py:_log_setup():526] Logging user logs to ./wandb/run-20240206_085917-0af4lsj8/logs/debug.log
2024-02-06 08:59:17,738 [1;36mINFO[1;0m MainThread:180571 [wandb_init.py:_log_setup():527] Logging internal logs to ./wandb/run-20240206_085917-0af4lsj8/logs/debug-internal.log
2024-02-06 08:59:17,738 [1;36mINFO[1;0m MainThread:180571 [wandb_init.py:_jupyter_setup():472] configuring jupyter hooks <wandb.sdk.wandb_init._WandbInit object at 0x7f39c85cb6a0>
2024-02-06 08:59:17,739 [1;36mINFO[1;0m MainThread:180571 [wandb_init.py:init():566] calling init triggers
2024-02-06 08:59:17,739 [1;36mINFO[1;0m MainThread:180571 [wandb_init.py:init():573] wandb.init called with sweep_config: {}
config: {}
2024-02-06 08:59:17,739 [1;36mINFO[1;0m MainThread:180571 [wandb_init.py:init():616] starting backend
2024-02-06 08:59:17,739 [1;36mINFO[1;0m MainThread:180571 [wandb_init.py:init():620] setting up manager
2024-02-06 08:59:17,741 [1;36mINFO[1;0m MainThread:180571 [backend.py:_multiprocessing_setup():105] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2024-02-06 08:59:17,742 [1;36mINFO[1;0m MainThread:180571 [wandb_init.py:init():628] backend started and connected
2024-02-06 08:59:17,761 [1;36mINFO[1;0m MainThread:180571 [wandb_run.py:_label_probe_notebook():1294] probe notebook
2024-02-06 08:59:17,761 [1;36mINFO[1;0m MainThread:180571 [wandb_run.py:_label_probe_notebook():1304] Unable to probe notebook: 'NoneType' object has no attribute 'get'
2024-02-06 08:59:17,762 [1;36mINFO[1;0m MainThread:180571 [wandb_init.py:init():720] updated telemetry
2024-02-06 08:59:17,850 [1;36mINFO[1;0m MainThread:180571 [wandb_init.py:init():753] communicating run to backend with 90.0 second timeout
2024-02-06 08:59:18,771 [1;36mINFO[1;0m MainThread:180571 [wandb_run.py:_on_init():2254] communicating current version
2024-02-06 08:59:18,873 [1;36mINFO[1;0m MainThread:180571 [wandb_run.py:_on_init():2263] got version response 
2024-02-06 08:59:18,873 [1;36mINFO[1;0m MainThread:180571 [wandb_init.py:init():804] starting run threads in backend
2024-02-06 08:59:23,913 [1;36mINFO[1;0m MainThread:180571 [wandb_run.py:_console_start():2233] atexit reg
2024-02-06 08:59:23,914 [1;36mINFO[1;0m MainThread:180571 [wandb_run.py:_redirect():2088] redirect: wrap_raw
2024-02-06 08:59:23,914 [1;36mINFO[1;0m MainThread:180571 [wandb_run.py:_redirect():2153] Wrapping output streams.
2024-02-06 08:59:23,914 [1;36mINFO[1;0m MainThread:180571 [wandb_run.py:_redirect():2178] Redirects installed.
2024-02-06 08:59:23,915 [1;36mINFO[1;0m MainThread:180571 [wandb_init.py:init():847] run started, returning control to user process
2024-02-06 08:59:23,916 [1;36mINFO[1;0m MainThread:180571 [jupyter.py:save_ipynb():373] not saving jupyter notebook
2024-02-06 08:59:23,917 [1;36mINFO[1;0m MainThread:180571 [wandb_init.py:_pause_backend():437] pausing backend
2024-02-06 08:59:23,923 [1;36mINFO[1;0m MainThread:180571 [wandb_init.py:_resume_backend():442] resuming backend
2024-02-06 08:59:23,968 [1;36mINFO[1;0m MainThread:180571 [jupyter.py:save_ipynb():373] not saving jupyter notebook
2024-02-06 08:59:23,969 [1;36mINFO[1;0m MainThread:180571 [wandb_init.py:_pause_backend():437] pausing backend
2024-02-06 08:59:23,975 [1;36mINFO[1;0m MainThread:180571 [wandb_init.py:_resume_backend():442] resuming backend
2024-02-06 08:59:23,977 [1;36mINFO[1;0m MainThread:180571 [jupyter.py:save_ipynb():373] not saving jupyter notebook
2024-02-06 08:59:23,977 [1;36mINFO[1;0m MainThread:180571 [wandb_init.py:_pause_backend():437] pausing backend
2024-02-06 08:59:23,985 [1;36mINFO[1;0m MainThread:180571 [wandb_init.py:_resume_backend():442] resuming backend
2024-02-06 08:59:23,989 [1;36mINFO[1;0m MainThread:180571 [jupyter.py:save_ipynb():373] not saving jupyter notebook
2024-02-06 08:59:23,990 [1;36mINFO[1;0m MainThread:180571 [wandb_init.py:_pause_backend():437] pausing backend
2024-02-06 08:59:24,000 [1;36mINFO[1;0m MainThread:180571 [wandb_init.py:_resume_backend():442] resuming backend
2024-02-06 09:02:41,584 [1;36mINFO[1;0m MainThread:180571 [jupyter.py:save_ipynb():373] not saving jupyter notebook
2024-02-06 09:02:41,584 [1;36mINFO[1;0m MainThread:180571 [wandb_init.py:_pause_backend():437] pausing backend
2024-02-06 09:02:41,590 [1;36mINFO[1;0m MainThread:180571 [wandb_init.py:_resume_backend():442] resuming backend
2024-02-06 09:02:41,591 [1;36mINFO[1;0m MainThread:180571 [wandb_run.py:_finish():1962] finishing run alps_with_swyft/lightning_logs/0af4lsj8
2024-02-06 09:02:41,591 [1;36mINFO[1;0m MainThread:180571 [jupyter.py:save_history():445] not saving jupyter history
2024-02-06 09:02:41,591 [1;36mINFO[1;0m MainThread:180571 [jupyter.py:save_ipynb():373] not saving jupyter notebook
2024-02-06 09:02:41,591 [1;36mINFO[1;0m MainThread:180571 [wandb_init.py:_jupyter_teardown():454] cleaning up jupyter logic
2024-02-06 09:02:41,592 [1;36mINFO[1;0m MainThread:180571 [wandb_run.py:_atexit_cleanup():2202] got exitcode: 0
2024-02-06 09:02:41,592 [1;36mINFO[1;0m MainThread:180571 [wandb_run.py:_restore():2185] restore
2024-02-06 09:02:41,592 [1;36mINFO[1;0m MainThread:180571 [wandb_run.py:_restore():2191] restore done
